### ISSUE TITLE
How to Trigger AWS Lambda Function in Airflow

### ISSUE THREAD

**Issue by benjamingregory** [astronomer/airflow-guides#10]
From Airflow Mailing List
```
Hi all,

Does anyone know of any tutorials or examples of triggering an aws lambda
function from airflow?

I googled a bit bit could not find much. I do see the aws_lambda_hook in
there but just a little unsure how to use it.

Cheers,
Andy
```

**Comment by vparekh94** [comment]
@benjamingregory we had someone ask for this with EE today - I'm going to try and take a crack at it

**Comment by tedmiston** [comment]
Here's how I would do it if interested - https://github.com/astronomerio/services/issues/510#issuecomment-415570858

**Comment by frankcash** [comment]
I will add an example for this!

**Comment by paolaperaza** [comment]
@ryw responding to your comment on [this commit](https://github.com/astronomerio/guides/commit/67ec4a875bb95cf2a9eb100d7edb65a79e2f7f0a#commitcomment-31240971)

I was collabing with @benjamingregory and we never shipped it. Ben, think you have time to give my draft above a look over?

**Comment by benjamingregory** [comment]
Closed with https://github.com/astronomer/airflow-guides/pull/103
