### ISSUE TITLE
Local vs. Celery vs. Kubernetes Executor guide

### ISSUE THREAD

**Issue by petedejoy** [astronomer/airflow-guides#104]
We need a guide detailing the different executors and their responsibilities. There really isn't anything great out there covering the differences and we get asked about them a lot. @vparekh94 or @benjamingregory - want to take a crack?

**Comment by petedejoy** [comment]
May as well add in Sequential and Mesos executors in here. @paolaperaza - here are some good resources I've found when trying to summarize executor concepts to prospects:

http://flagzeta.org/blog/how-apache-airflow-works/
https://medium.com/@dustinstansbury/understanding-apache-airflows-key-concepts-a96efed52b1a
https://airflow.apache.org/howto/executor/use-celery.html
https://airflow.apache.org/howto/executor/use-mesos.html

**Comment by paolaperaza** [comment]
Great, thanks @petedejoy - I'll throw in a draft here once I have it

**Comment by paolaperaza** [comment]
Draft tracked in this google doc: https://docs.google.com/document/d/1CU_vw-SBLyzSSKLCIgOfkkd-yzhNEWtpZViGZnAP16M/edit

**Comment by paolaperaza** [comment]
Aaaand this is done! 

Tweeted and officially live on the internet: https://www.astronomer.io/guides/airflow-executors-explained/
