### ISSUE TITLE
Migrating from Composer to Astronomer guide

### ISSUE THREAD

**Issue by vparekh94** [astronomer/airflow-guides#106]
We should have a guide for future customers that chose to migrate

**Comment by vparekh94** [comment]
Off the top of my head:

1) Ensure you are using the right version of airflow

2) Get all your needed python packages into a `requirements.txt`

3) Whitelist our IP

4) Get your connection info into Astronomer. You might need to change how your code references credentials (@benjamingregory - your code snippet from Slack could help here)

**Comment by paolaperaza** [comment]
This is cool, thanks for working on this 🙏
