### ISSUE TITLE
How to Deploy to Astro Cloud via Bitbucket

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/airflow-guides#116]
### How to Deploy to Astronomer Cloud via Bitbucket

- Customer would push to Astronomer's private registry (no DockerHub account needed)
- References:
    - https://confluence.atlassian.com/bitbucket/run-docker-commands-in-bitbucket-pipelines-879254331.html
    - https://confluence.atlassian.com/bitbucket/configure-bitbucket-pipelines-yml-792298910.html'
- Clarification that calling `docker login registry.astronomer.cloud -u _ -p $${ASTRONOMER_PASSWORD}` there is no API name required, only API key is needed
-  With release name and bitbucket info swapped out, it'd look something like:

```pipeline:
  build:
    image: astronomerio/ap-build:0.0.7
    commands:
      - docker build -t registry.astronomer.cloud/infrared-photon-7780/airflow:ci-${DRONE_BUILD_NUMBER} .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: push
      branch: [ master, release-* ]

  push:
    image: astronomerio/ap-build:0.0.7
    commands:
      - echo $${DOCKER_PASSWORD_TEST}
      - docker login registry.astronomer.cloud -u _ -p $${DOCKER_PASSWORD_TEST}
      - docker push registry.astronomer.cloud/infrared-photon-7780/airflow:ci-${DRONE_BUILD_NUMBER}
    secrets: [ docker_password_test ]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      event: push
      branch: [ master, release-* ]
```

Follow up questions from a customer:

> 1. What it `{DOCKER_PASSWORD_TEST}` and `{DRONE_BUILD_NUMBER}` in your script? Right now we only use token to login astronomer cloud, how could we setup secrets for deployment?

> 2. what is the function of `volumes: - /var/run/docker.sock:/var/run/docker.sock` in the script? could you please check if we have similar function for bitbucket here? https://confluence.atlassian.com/bitbucket/configure-bitbucket-pipelines-yml-792298910.html

> 3. regarding image, `image: astronomerio/ap-build:0.0.7` in your script is public build image or private build image? refer to: https://confluence.atlassian.com/bitbucket/use-docker-images-as-build-environments-792298897.html

> 4. any hiden variables I need to set up in pipelines? refer https://confluence.atlassian.com/bitbucket/variables-in-pipelines-794502608.html

**Comment by paolaperaza** [comment]
@andrewhharmon @vparekh94 Would either of you have time to look into this?

It looks like the questions are relatively basic, but I can go from there to put this together and publish to the right place/get back to customer.

**Comment by vparekh94** [comment]
That environment variable (DOCKER_PASSWORD_TEST). is the service account API key generated that lets you log into the registry to push an image. It is equivalent to the Bitbucket Variable:
https://confluence.atlassian.com/bitbucket/run-docker-commands-in-bitbucket-pipelines-879254331.html
(see authenticating to a registry).

https://confluence.atlassian.com/bitbucket/variables-in-pipelines-794502608.html

The build number refers to the tag of the built image - it should be incremented every code push - incrementing this tag tells our API that a new image has been pushed and initiates a full deployment.


The `volume` piece is syntax that is related to how to run docker services on Drone. Volume indicates that there is going to be a mounted volume when building the image.

For bitbucket specific build steps, I would refer to the examples that bitbucket shows on how to build docker images . It looks like you just have to specify that the docker service is running (first link):

All Astronomer images are public, so you should not have any issues pulling down the `ap-build:0.0.7` image.


When you kick off a deploy with the CLI, the image is built, tagged, and pushed into a registry named for your deployment. As such, we should be able to integrate with any CI tool that supports Docker (tho each CI tool will have different syntax).

**Comment by nevinjiang** [comment]
There is no `volume` command in bitbucket: https://confluence.atlassian.com/bitbucket/configure-bitbucket-pipelines-yml-792298910.html

Is this critical for astronomer pipeline? any alternatives?

**Comment by nevinjiang** [comment]
I have this script based on bitbucket pipeline instruction, please review and let me know if I missed something:
`pipelines:
  default:
    - step:
        image: astronomerio/ap-build:0.0.7
        script:
          - docker build -t registry.astronomer.cloud/positional-bolide-0394/airflow:ci-${BITBUCKET_BUILD_NUMBER} .
        services:
          - docker
        caches:
          - docker

  branches:
    master:
      - step:
          image: astronomerio/ap-build:0.0.7
          script:
            - echo $${ASTRONOMER_PASSWORD}
            - docker login registry.astronomer.cloud -u _ -p $${ASTRONOMER_PASSWORD}
            - docker push registry.astronomer.cloud/positional-bolide-0394/airflow:ci-${BITBUCKET_BUILD_NUMBER}
          services:
            - docker
          caches:
            - docker`

**Comment by nevinjiang** [comment]
I'd like to share with you my success deployment yaml for bitbucket
```
image: astronomerio/ap-build:0.0.7

pipelines:
  branches:
    master:
      - step:
          name: Deploy to production
          deployment: production
          script:
            - echo ${ASTRONOMER_PASSWORD}
            - docker login registry.astronomer.cloud -u _ -p ${ASTRONOMER_PASSWORD}
            - docker push registry.astronomer.cloud/infrared-photon-7780/airflow:ci-${BITBUCKET_BUILD_NUMBER}
          services:
            - docker
          caches:
            - docker

**Comment by paolaperaza** [comment]
Thanks, @nevinjiang !

**Comment by vparekh94** [comment]
@nevinjiang would you mind if we put this sample script in our docs?

**Comment by nevinjiang** [comment]
not at all. Please feel free to do so.

**Comment by nevinjiang** [comment]
Please let me double check with Nick.

**Comment by nevinjiang** [comment]
@vparekh94 Please go ahead put the script in your docs. It would be great if you could mention us as your partner and linked back to us.

**Comment by vparekh94** [comment]
@nevinjiang done!

https://github.com/astronomer/docs/commit/c48f73751a7b02021e63dffb88b93f82af058ccd
