### ISSUE TITLE
Clean up DAG Best Practice Guide

### ISSUE THREAD

**Issue by jwitz** [astronomer/airflow-guides#163]
@petedejoy commented on [Fri Feb 22 2019](https://github.com/astronomer/issues/issues/275)

This is the highest-performing guide (and one of the highest performing pages!) on our site. @andrewhharmon - want to take a crack at running thru it and fixing it up a bit? We wrote it a while back and @vparekh94 mentioned that there are updates that can be made.

[Find the guide here](https://astronomer.io/guides/dag-best-practices) and the [Markdown file here](https://github.com/astronomer/airflow-guides/blob/master/guides/dag-best-practices.md). Let me know if you need a hand getting set up contributing, but everything you need to know should be in the README for this repo.

**Comment by kentdanas** [comment]
Done and published here: https://www.astronomer.io/guides/dag-best-practices
