### ISSUE TITLE
UnitTesting DAGs Guide

### ISSUE THREAD

**Issue by jwitz** [astronomer/airflow-guides#164]
@vparekh94 commented on [Wed Aug 22 2018](https://github.com/astronomer/issues/issues/279)

We should give some advice on unit-testing DAGs - a few customers have asked for it and there isn't much online about it.

Inspired by:
https://blog.usejournal.com/testing-in-airflow-part-1-dag-validation-tests-dag-definition-tests-and-unit-tests-2aa94970570c

Assigning @benjamingregory but no reason he has to be the one to do it, he'll just make sure it gets done :smile:  

---

@paolaperaza commented on [Thu Jul 18 2019](https://github.com/astronomer/issues/issues/279#issuecomment-512823019)

Bumping this back up as we saw it pop up again in the Airflow emailing list: https://lists.apache.org/thread.html/ca71d73d83a17a95e1aad771316e63c7be8f35625f400cedcc18aa8e@%3Cdev.airflow.apache.org%3E

Some recent feedback from a customer:

> The impetus for setting up unit tests today is that I am trying to write an sla_miss callback that will send alarms to cloudwatch. I'm hoping to be able to test that callback through unit tests - doesn't seem easy to test any other way.
> 
> Generally we want to have unit tests both on the custom hooks and operators and helper functions we've been writing but also on DAG configuration to catch issues before we deploy. I'm hoping to hook these up to run in Circle CI and block merging of PRs. I'm thinking of adding checks along the lines of the Testing section in this Blog post (https://wecode.wepay.com/posts/airflow-wepay), as well as checks that all `ExternalTaskSensor` point to DAG/Tasks that exist. Anything that can prevent bugs in DAG configs from getting deployed or help enforce best practices and standardization.
> 
> This feels like generically best practice and would be cool to see that baked into astronomer a little more: a `test` folder as a first class citizen, a best practices guides with some examples. I'd be happy to share whatever we get set up once we get it working if that would be helpful in promoting that to more astro/airflow users.

@andrewhharmon @ashb Think one of you can write up a skeleton of this?

---

@jwitz commented on [Wed Dec 09 2020](https://github.com/astronomer/issues/issues/279#issuecomment-741894343)

@paolaperaza Was there anything we wanted to publish here that isn't already covered by this guide? https://airflow.apache.org/docs/apache-airflow/stable/best-practices.html#unit-tests

---

@jwitz commented on [Tue Dec 15 2020](https://github.com/astronomer/issues/issues/279#issuecomment-745309317)

This seems like content that belongs in an Airflow Guide rather than our own docs, so I'm closing this issue and opening a new one in the `airflow-guides` repo.

**Comment by kentdanas** [comment]
Done here: https://www.astronomer.io/guides/testing-airflow
