### ISSUE TITLE
Add docs/best practices for KEDA (Airflow Docs)

### ISSUE THREAD

**Issue by jwitz** [astronomer/airflow-guides#165]
@paolaperaza commented on [Mon Aug 17 2020](https://github.com/astronomer/issues/issues/1670)

There's an issue in the core Apache Airflow repo to add documentation around KEDA. As advocates for KEDA, Astronomer should help provide open-source docs.

Airflow Issue here: https://github.com/apache/airflow/issues/10358

We'll _additionally_ have docs around KEDA for the Astronomer Platform to be tracked separately.

**Comment by kentdanas** [comment]
Closing this since it's not related to our Guides
