### ISSUE TITLE
Add how-to Guide for Postgres operators

### ISSUE THREAD

**Issue by jwitz** [astronomer/airflow-guides#169]
@Dr-Denzy commented on [Thu Dec 10 2020](https://github.com/astronomer/issues/issues/2349)

Description

A guide that describes how to use all the operators for Postgres (https://github.com/apache/airflow/tree/master/airflow/providers/postgres) would be useful.

Other guides are available:
https://airflow.readthedocs.io/en/latest/howto/operator/index.html

Source code for those guides are at:
https://github.com/apache/airflow/tree/master/docs/howto/operator

OSS: https://github.com/apache/airflow/issues/11917

**Comment by kentdanas** [comment]
I think this is accomplished well enough through our guide on executing SQL with Airflow (https://www.astronomer.io/guides/airflow-sql-tutorial) and the Postgres provider documentation and example DAGs on the registry (https://registry.astronomer.io/providers/postgres/modules/postgresoperator)
