### ISSUE TITLE
Publish KubernetesExecutor 2.0 Blog Post on Astronomer (w/ 1.10.13)

### ISSUE THREAD

**Issue by jwitz** [astronomer/airflow-guides#171]
@paolaperaza commented on [Mon Sep 07 2020](https://github.com/astronomer/issues/issues/1757)

@dimberman Has a draft going for a blog post that informs users of the recent rewrite of the KubernetesExecutor shipped with Airflow 1.10.13 and 2.0.

Draft on Notion here: https://www.notion.so/astronomerio/The-New-KubernetesExecutor-065dc1e624c04ad7b1b56cd1b0fbaf78

The intention is for this to be published on the Astronomer blog - creating this issue to track that work. Can close out when it's published.

**Comment by kentdanas** [comment]
Done and published here: https://www.astronomer.io/blog/new-kubernetesexecutor
