### ISSUE TITLE
How to Use Airflow SLA's

### ISSUE THREAD

**Issue by jwitz** [astronomer/airflow-guides#173]
@paolaperaza commented on [Thu Aug 01 2019](https://github.com/astronomer/issues/issues/268)

We've gotten a few comments in the last few weeks about customers looking for best practices around using Airflow's SLA functions (e.g. `airflow_miss_callback`).

From a customer:

> Just curious if any of you all have any advice around Airflow SLAs, especially with a custom callback function. I'm trying to force an SLA miss locally, and it shows up if I browse for it, but I don't see anything... happening. Is the callback executed within the context of a task? Would I see logs from it in the task logs? Somewhere else?

Resources referenced:
- https://github.com/DFStoneburner/airflow-sla-examples/blob/master/basic_sla.py

---

@jwitz commented on [Tue Dec 08 2020](https://github.com/astronomer/issues/issues/268#issuecomment-740962727)

@paolaperaza Just realized we don't have a great distinction between requests for documentation and requests like this, which seems more suited for https://github.com/astronomer/airflow-guides. Should I close this as a doc issue for the time being?

**Comment by kentdanas** [comment]
This was taken care of in an update to our error notifications guide: https://www.astronomer.io/guides/error-notifications-in-airflow
