### ISSUE TITLE
Airflow Guide on support for Airflow Backport Providers

### ISSUE THREAD

**Issue by jwitz** [astronomer/airflow-guides#175]
@paolaperaza commented on [Wed Aug 19 2020](https://github.com/astronomer/issues/issues/1688)

In Airflow 2.0 - following [AIP-21 "change in import paths"](https://cwiki.apache.org/confluence/display/AIRFLOW/AIP-21%3A+Changes+in+import+paths) all the non-core interfaces to Airflow's external systems have been moved to the `airflow.providers` package.

Hooks, operators, sensors and secrets from Airflow 2.0 can be used in Airflow 1.10.x as separately installable packages. We don't currently have documentation or clear guidance for users on:

- Context for `airflow.providers`
- How to install backport packages
- How to find changes between current packages and 2.0 packages
- Explicitly state constraint that `airflow.providers` packages can only be used in a Python3.6+ environment

This doc should live in /guides (Airflow Guides) on Astronomer AND should be referenced in the "Customize your Image" doc on Astronomer.

In progress doc here from @kaxil: https://www.notion.so/astronomerio/Installing-Backport-Packages-4befc55e4e73430ca22886c36605a3bb

**Comment by kentdanas** [comment]
Backport providers are no longer supported and have been removed from the Airflow project (PR here: https://github.com/apache/airflow/pull/14886) - guide request no longer relevant.
