### ISSUE TITLE
Dynamically Generated dags execute on min_file_process_interval, not scheduler heartbeat

### ISSUE THREAD

**Issue by collinmcnulty** [astronomer/airflow-guides#233]
I believe that dag files are processed every [min_file_process_interval](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#min-file-process-interval) not every [scheduler heartbeat](https://airflow.apache.org/docs/apache-airflow/stable/configurations-ref.html#scheduler-heartbeat-sec). By default, there is a 30x difference in these times (30s vs 1 s).

Our guide on [dynamically generating dags](https://www.astronomer.io/guides/dynamically-generating-dags) repeatedly says it's the scheduler heartbeat, but I believe this is inaccurate.

**Comment by collinmcnulty** [comment]
@jedcunningham can you confirm?

**Comment by jedcunningham** [comment]
Basically, yes.

Not _always_ though. It can be more frequent when mtime is bumped, or it can be (much) longer if it takes longer to do a full parsing cycle (think lots of DAGs).

**Comment by collinmcnulty** [comment]
So the line "If the DAG parsing time (i.e. the time to parse all code in the DAG_FOLDER) is greater than the Scheduler heartbeat interval, the scheduler can get locked up and tasks won't be executed" is just not true at all then? It'll just take as long as it takes to parse all the dags and then start again once it's done?

**Comment by jedcunningham** [comment]
Yeah, exactly.

And on top of that, in Airflow 2 DAG parsing and scheduling are more or less decoupled.  Airflow 1 was susceptible to scheduling delays, but even it wouldn't lock up if you had a high total DAG parsing time, so I'm not sure that was ever right?
