### ISSUE TITLE
Parsing processes advice accuracy

### ISSUE THREAD

**Issue by collinmcnulty** [astronomer/airflow-guides#308]
https://github.com/astronomer/airflow-guides/blob/main/guides/airflow-scaling-workers.md?plain=1#L79

Is the advice given about parsing_processes really accurate? It really only helps parse more dags faster, it doesn't help with the actual scheduling. Walmart is asking about scale and they brought up increasing parsing processes, but I don't think that's very sound.

**Comment by wolfier** [comment]
> **`parsing_processes`** is the maximum number of threads that can run on the Airflow Scheduler at once. Increasing the value of `parallelism` results in additional strain on the Scheduler, so we recommend increasing `parsing_processes` as well. If you notice a delay in tasks being scheduled, you might need to increase this value or provision additional resources for your Scheduler.

I believe this suggestion is no longer true for Airflow 2.0+.

In Airflow 2.0, the `DagFileProcessorProcess` now only process files, which ultimately means that it serializes DAGs. You can read more about the `DagFileProcessorProcess` and `DagProcessorManager` in the [Airflow documentation](https://airflow.apache.org/docs/apache-airflow/2.2.3/concepts/scheduler.html#dag-file-processing).

The [documentation](https://airflow.apache.org/docs/apache-airflow/2.2.3/concepts/scheduler.html#overview) also states:

> the scheduling decision making has been moved from the DagFileProcessors to the SchedulerJob.

The scheduler uses the serialized DAG representation (recorded by the `DagFileProcessorProcess`) to make its scheduling decisions.

---

For tasks stuck in queued for an extended time, we will need to inspect where the root issue is.

* Scheduler
    * max_dagruns_per_loop_to_schedule
    * max_tis_per_query
    * max_active_tasks_per_dag
    * pool slots
* Executor
    * parallelism
* Worker
    * resources (namespace resource quota / limit range / pod resources)
    * execution error
