### ISSUE TITLE
CustomLogging - Using an external logging service

### ISSUE THREAD

**Issue by stuart23** [astronomer/airflow-guides#309]
I put together a guide for a customer wanting to use an external elasticsearch deployment: https://docs.google.com/document/d/18khnOK7bRabDpxBMj0KSMLGewDC19hLVXNPHpVrpZW4/

This guide extends the WIP guide(s) here: https://www.notion.so/astronomerio/External-Elasticsearch-Integration-WiP-d5b691bc7b844b2aad6ddec2d9d18c67

The WIP guide on notion has some of the config parameters wrongly named, and I have included a few more steps in mine.

**Comment by stuart23** [comment]
@pgvishnuram I added some more information/corrections. We can merge the documents to notion if an official guide is not created.

**Comment by pgvishnuram** [comment]
index pattern will be fluentd.*

**Comment by stuart23** [comment]
Thanks @pgvishnuram - I have updated the document to correct this now.

**Comment by kentdanas** [comment]
Hey @stuart23, is this meant for Astronomer Enterprise users (that was my interpretation from the notion doc)? Our guides site is generally focused on OSS Airflow. So if this is a "how-to" for Astronomer customers, it would be better suited for our docs. Instructions for submitting a docs request are [here](https://www.notion.so/astronomerio/Submitting-a-Documentation-Request-Issue-38fd8c3918384144bb4a9600589e0ec8), or you can post in #docs on slack if you have questions

**Comment by stuart23** [comment]
Hi @kentdanas. I'm sorry I was just passed a link to this repo and didn't even check the repos name! I'll close this and reopen it in the docs repo.

**Comment by kentdanas** [comment]
All good! We throw the term "guide" around a lot, and there's definitely overlap between guides/docs, so it can be confusing sometimes
