### ISSUE TITLE
Update filepath to config_filepath

### ISSUE THREAD

**Issue by magdagultekin** [astronomer/airflow-guides#319]
https://github.com/astronomer/dynamic-dags-tutorial/blob/main/include/generate-dag-files.py

In the line 11 of the code `filepath` should be changed to `config_filepath`.

Also, the screenshot in the guide below should be updated:
https://www.astronomer.io/guides/dynamically-generating-dags

**Comment by kentdanas** [comment]
@magdagultekin thanks for catching this, I'll get it updated. Which screenshot are you referring to?

**Comment by magdagultekin** [comment]
@kentdanas oh yes, correct :)
