### ISSUE TITLE
Update references to "Astronomer Cloud" across Airflow Guides

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/airflow-guides#325]
As we prep for a public launch of Gen2Cloud, we should clean up our references to `Astronomer Cloud` across our Guides. The vast majority of them are outdated and do not reflect our current functionality or purpose. Examples include:

- "Astronomer Cloud is currently on Airflow 1.8"
- "KubernetesPodOperator Support for Astronomer Cloud is coming soon"

We should just search any instances of "Cloud" or "Astronomer Cloud" and remove or update those references 😊  cc: @astrorfox 

![image (2)](https://user-images.githubusercontent.com/31111752/151708742-2466b66b-9fff-454e-a0db-497366d5b16b.png)

**Comment by kentdanas** [comment]
Hey @paolaperaza thanks for bringing this to my attention! Some of the references in your screenshot above don't seem to be in our Guides repo, and a few are in our "guides in progress" folder, which aren't published and are all legacy (won't be published, just haven't been cleaned up yet). 

But, for the references in our guides I've gone through and removed or updated all of them in this PR: https://github.com/astronomer/airflow-guides/pull/336
Would appreciate your review - let me know if I got all the naming right or if I missed anything!
