### ISSUE TITLE
Remove pool usage or note pool usage in deferrable operator example

### ISSUE THREAD

**Issue by frankcash** [astronomer/airflow-guides#327]
In https://www.astronomer.io/guides/deferrable-operators there are two pools used, we should either remove the usage of these pools or add an info / note label to create the pools

**Comment by kentdanas** [comment]
@ReadytoRocc are the pools needed for the example here? I can take care of the update, but not sure whether you intended to include them in the context of the example.

**Comment by ReadytoRocc** [comment]
@kentdanas, no they are not needed. Please feel free to remove them.
