### ISSUE TITLE
Improve Custom XCom back-end guide w/ more details for local testing

### ISSUE THREAD

**Issue by frankcash** [astronomer/airflow-guides#332]
Currently the custom [xcom back-end guide](https://www.astronomer.io/guides/custom-xcom-backends) details writing to a live bucket, which is fine for a dev/qa/prod environment.  

It would be nice to detail a better way to get this running with all local infrastructure. This can be down with [minio](https://github.com/minio/minio) or [localstack](https://github.com/localstack/localstack)

If not there should be a linkage of utilizing the docker-compose override documents for someone to work it out on their own.

**Comment by kentdanas** [comment]
Migrated issue to the docs repo, we'll take care of it there.
