### ISSUE TITLE
Update Introduction to Kubernetes

### ISSUE THREAD

**Issue by magdagultekin** [astronomer/airflow-guides#338]
Some minor things: 

![image](https://user-images.githubusercontent.com/97064715/154255002-31ca0fa9-c203-49ee-a4bd-1acf22eac378.png)

![image](https://user-images.githubusercontent.com/97064715/154255264-8a90d884-477b-4cc4-a62c-807f1c4b0d12.png)

![image](https://user-images.githubusercontent.com/97064715/154255543-b4160503-c2e2-4fe2-b4e7-fc5570acaa32.png)

**Comment by kentdanas** [comment]
Thanks for catching these @magdagultekin! This guide definitely needs an update overall, but for now I fixed those typos in a PR here: https://github.com/astronomer/airflow-guides/pull/341
