### ISSUE TITLE
Airflow 101 Guide

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/airflow-guides#35]
We need to build an introductory guide to Apache Airflow - right now we have that material in a bunch of different places, but it's not consolidated. 

It'd likely look like a mix of the following:
- https://docs.astronomer.io/v2/apache_airflow/tutorial/core-airflow-concepts.html
- https://www.astronomer.io/guides/intro-to-airflow/
- https://airflow.apache.org/tutorial.html
- https://medium.com/@dustinstansbury/understanding-apache-airflows-key-concepts-a96efed52b1a
- https://github.com/astronomerio/spacecamp/tree/master/notebooks/day1

**Comment by vparekh94** [comment]
@paolaperaza is this still relevant?

**Comment by paolaperaza** [comment]
I'm not sure - I would say it's definitely not high priority, but it wouldn't be the worst thing for us to have our own original version of "What is Apache Airflow." Right now there's a ton of external content (and apache documentation) that fills this gap - so I suppose it's just a question of whether or not we wanted to forever send people towards that, or eventually have something ourselves.

Keep it open for now?

**Comment by paolaperaza** [comment]
Closing out this issue in favor of #56
