### ISSUE TITLE
Launch K8s pods in other clusters using Astro

### ISSUE THREAD

**Issue by collinmcnulty** [astronomer/airflow-guides#367]
Customers want to launch pods that interact with their resources in their own cloud accounts. The architecture of Astro forces them to use a separate account for their data plane, so this makes these cross-cluster and cross-account pod deployments.

**Comment by collinmcnulty** [comment]
@manmeetkaur wrote this Notion page that is a great start for this guide

https://www.notion.so/astronomerio/Astro-KPO-remote-EKS-Cluster-56ab0e4600c34c7f8973a72394134df6

**Comment by kentdanas** [comment]
@paolaperaza relevant for the Astro tutorials vs Airflow guides discussion. I would think this would lend itself to the former

**Comment by kentdanas** [comment]
@collinmcnulty FYI, since this repo is frozen for changes now I've migrated the issue over to the docs repo. We'll take care of it there, so I'm closing this one.
