### ISSUE TITLE
Test KPO Locally, using astro dev

### ISSUE THREAD

**Issue by alex-astronomer** [astronomer/airflow-guides#368]
I'm intending this guide be a (somewhat) opinionated look into how I test KPO locally using `astro dev` and a local Docker-owned k8s "cluster".

Going to write this out and see what y'all think!

**Comment by kentdanas** [comment]
@alex-astronomer we just published an update to our [KPO guide](https://www.astronomer.io/guides/kubepod-operator) that now includes a section on local development. It's not super detailed, but curious if it satisfies what you were thinking. If not, we may want an astro-focused tutorial (we're launching these soon) on this topic to complement the guide.

**Comment by kentdanas** [comment]
@alex-astronomer all future guide updates are going to happen in the docs repo, so I'm closing this here. If our existing KPO guide section on local development doesn't address your need definitely let us know by submitting an issue in the docs repo!
