### ISSUE TITLE
New guide on accessing dagrun context

### ISSUE THREAD

**Issue by RNHTTR** [astronomer/airflow-guides#393]
There's not a lot of info on accessing a dagrun's context, and what exists in the airflow docs is hard to find or unclear. For example, the [section on accessing current context](https://airflow.apache.org/docs/apache-airflow/2.0.2/concepts.html#accessing-current-context) seems to have been removed since 2.1.0, and the [template reference](https://airflow.apache.org/docs/apache-airflow/stable/templates-ref.html) doesn't make it clear that how to access the values it describes in a DAG (or even that you _can_ access them outside of jinja).

This _could_ go into the [templating guide](https://www.astronomer.io/guides/templating), but IMO this topic warrants its own guide as it's not exactly the same as templating.

**Comment by kentdanas** [comment]
Migrated this issue to the docs repo: https://github.com/astronomer/docs/issues/1279. We'll tare care of it there post-guides migration.
