### ISSUE TITLE
Guide on set up for developing on core Airflow

### ISSUE THREAD

**Issue by vparekh94** [astronomer/airflow-guides#42]
There's no community guide on how to get started debugging core airflow stuff. Since we just got @rhwang10 set up on it, it'd be great to contribute something back about it!

**Comment by rhwang10** [comment]
starting work on this now, hoping to have something to review by EOW

**Comment by andscoop** [comment]
Be sure to use CONTRIBUTING.md as a reference

https://github.com/apache/incubator-airflow/blob/master/CONTRIBUTING.md

**Comment by vparekh94** [comment]
@rhwang10 any update on this?

**Comment by rhwang10** [comment]
Yep, I wrote out a rough outline for developing w/ docker, haven't had a chance to sit down w/ Andy yet to go over the airflow PR. Will want to put the kube-metrics stuff in too when it's up and running

**Comment by vparekh94** [comment]
@rhwang10 how is this looking?

**Comment by rhwang10** [comment]
@vparekh94 haven't touched much airflow stuff since I started working on logs- i think I could come back to it once platform stabilizes a bit more

**Comment by rhwang10** [comment]
No plans to address this for now
