### ISSUE TITLE
Error in scheduling guide for version with Timetables

### ISSUE THREAD

**Issue by collinmcnulty** [astronomer/airflow-guides#436]
> In versions of Airflow 2.2 and earlier, specifying schedule_interval is the only way to define a DAG’s schedule.

I think we mean "before 2.2". Timetable is an option in 2.2.

**Comment by kentdanas** [comment]
Thanks for catching this @collinmcnulty! I'm fixing this as we migrate this guide since we've frozen changes on this repo for now.
