### ISSUE TITLE
Guide on EE Airflow and GDPR compliance

### ISSUE THREAD

**Issue by vparekh94** [astronomer/airflow-guides#50]
We should have something that shows how EE airflow is GDPR compliant, especially since we've been talking to a lot of European companies recently.

Most of the major cloud providers have a ton of docs about how GDPR compliant they are, so we should just be able to steal most of those
https://cloud.google.com/blog/topics/inside-google-cloud/google-cloud-ready-for-gdpr
https://aws.amazon.com/compliance/gdpr-center/service-capabilities/

**Comment by vparekh94** [comment]
@petedejoy @paolaperaza would it make sense to close this and open another one around something that outlines the security stuff you both are working on?

**Comment by paolaperaza** [comment]
@vparekh94 Yes. Closing this out in favor of https://github.com/astronomer/airflow-guides/issues/80
