### ISSUE TITLE
Guide on Resource Defaults and Config

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/airflow-guides#67]
We got a question from Pivotal (EE) that read:

> Q1: Is there any doc/architecture diagram that I can find out the usage/purpose of the airflow cluster pods(like flower pgbouncer, redis)? How are the resources(CPU, RAM) of these components defined/or to be modified?

Part I is answered [here](https://www.astronomer.io/guides/astronomer-features/), but we should have a guide that walks a user through resource defaults , management, and config that fits with v0.7.0 guidelines. 

Worker specs are listed in an FAQ in [this guide](https://www.astronomer.io/guides/getting-started-with-new-cloud/).

**Comment by vparekh94** [comment]
Platform level resource constraints can be found here:
https://github.com/astronomerio/helm.astronomer.io/blob/a57a4814b7eaf05d3b17a79972a0acf4ccc3916d/values.yaml

We should probably also have some sort of "How to know what to scale" type guide to help EE users scale their cluster accordingly (what's a sign of an overloaded scheduler? Do I need to add more CPU or memory?)

**Comment by vparekh94** [comment]
Closing this as most of it is covered with the new UI
