### ISSUE TITLE
Equivalent of performing spark dataframe window function in Airflow

### ISSUE THREAD

**Issue by vparekh94** [astronomer/airflow-guides#76]
From a customer:

There are application logs stored in some tables.  Each table corresponds to an event type, and has columns of event metadata.....

I would like to do is append the columns from the startup table to the other tables, but my join needs to look something like this:
WHERE startup.user_id = othertable.user_id AND startup.timestamp = greatest startup.timestamp value that occurred before othertable.timestamp

I believe I can accomplish this in glue using sparc dataframe window functions, but I have not yet worked out how to do this in airflow.  Do you guys have any suggestions?

**Comment by paolaperaza** [comment]
@vparekh94 @benjamingregory either of you takin a first kick at this?

**Comment by ryw** [comment]
Can we post this to https://forum.astronomer.io/ and I'm happy to try to promote to Airflow community for possible answer.

**Comment by stevebiomatters** [comment]
Thanks that makes sense.  I don't want to constrain on memory, so pandas dataframes probably isn't a good option.  We had initially tried to do this in the database, but Redshift does not seem to support the window functions I would need.  Is it possible to use Sparc dataframes directly from Airflow?  That might be an option.  I'll also see whether I can make a solution using a UDF.

**Comment by vparekh94** [comment]
Which spark dataframes are you referring to? PySpark? or are you used to using some sort of other tool?

**Comment by stevebiomatters** [comment]
This is the framework I have been using in Glue:

https://spark.apache.org/docs/latest/sql-programming-guide.html

Glue uses its own DynamicFrames which wrap and provide convenience functions around these Spark Dataframes, so you typically write your code reference DynamicFrames, then drop out of them into DataFrames when you need functionality that DynamicFrames do not support.


In the meantime I think I have found a way to do what I want using the SQL that Redshift supports natively, so I am now working on writing some Airflow Operators that do what I want by running SQL commands on the database.  Nevertheless I would like to fully test Airflow's ETL capabilities so would also like to get something running using the above dataframes or similar.

**Comment by vparekh94** [comment]
@stevebiomatters sorry this fell off of our radar, but looks like it can be closed!
