### ISSUE TITLE
Add note on renewing cert

### ISSUE THREAD

**Issue by paolaperaza** [astronomer/airflow-guides#79]
Relevant Docs:

- [EE Operator Guide](https://www.astronomer.io/docs/ee-administration-devops/)
- [SSL Cert](https://www.astronomer.io/docs/ee-installation-ssl/?_ga=2.213643476.1177944017.1542125218-780968402.1526312462)

Q: How can I auto renew the SSL certificate if just have a one time certificate that will expire?

> "We have some customers who have implemented cert manager through kube-lego to auto renew their cert, more about that here: http://docs.cert-manager.io/en/latest/index.html
> 
> In the meantime you can generate a new short lived certificate and follow the same process to recreate your `astronomer-tls` secret after deleting the current one.
> 
> After updating this secret you will want to restart the `houston`, `nginx` and `registry` pods to ensure they pick up the new certificate.

**Comment by vparekh94** [comment]
@paolaperaza how's this looking?

**Comment by vparekh94** [comment]
@paolaperaza bump.

**Comment by paolaperaza** [comment]
Fixed: https://www.astronomer.io/docs/ee-installation-ssl/

Note added:

> To renew your cert, you have two options:

   > (1) Set to auto renew via a cert manager through kube-lego. More info about that here: http://docs.cert-manager.io/en/latest/index.html
   > (2) Generate a new short lived certificate and follow the same process to recreate your astronomer- tls secret after deleting the current one.

> Note: After updating your secret, you'll also want to restart the houston, nginx and registry pods to ensure they pick up the new certificate.
