### ISSUE TITLE
Detailed guide for getting marketo data into Redshift using Apache airflow

### ISSUE THREAD

**Issue by Arsalan9002** [astronomer/airflow-guides#82]
there is no detailed guide for getting marketo data into Redhshift using airflow LIKE how to make connections for s3, redshift and marketo in apache airflow UI.

I am running astronomer.

**Comment by vparekh94** [comment]
HI @Arsalan9002 have you checked out these resources?:

https://github.com/airflow-plugins/marketo_plugin

https://github.com/airflow-plugins/Example-Airflow-DAGs/blob/master/etl/marketo_to_redshift.py

**Comment by vparekh94** [comment]
@Arsalan9002 closing this for now - feel free to open up an additional issue  if needed
