### ISSUE TITLE
Doc integrating Okta with Astronomer

### ISSUE THREAD

**Issue by vparekh94** [astronomer/airflow-guides#98]
We should have a doc walking someone how to do it

**Comment by paolaperaza** [comment]
From schnie:

We don't have any official docs on this, but we should add. By default the system uses a shared auth0 account that we manage. To use your own auth0 account, all you should need to do is create the auth0 account and plug your values here: https://github.com/astronomer/helm.astronomer.io/blob/master/charts/astronomer/values.yaml#L44-L48.
charts/astronomer/values.yaml:44-48
  ```auth0:
    enabled: true
    clientId: "rH2L4yKctlepniTyJW3MkuXuTreOHHn1"
    baseDomain: "astronomerio.auth0.com"
    externalLogin: false```
 Show more
astronomer/helm.astronomer.ioAdded by GitHub
These values are nested in the `astronomer` chart, so your `config.yaml` will need to have these values nested under `astronomer.auth.auth0`

**Comment by vparekh94** [comment]
Rough draft with https://github.com/astronomer/astronomer/commit/c03a2bc5d8336e4ddc498e5088b555dbfdb0e154

Enough to close for now
